/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // HOME
    {
      type: 'html',
      value: '<div class="sidebar__section">HOME</div>',
      defaultStyle: true,
    },
    'intro',
    {
      type: 'category',
      label: 'READ ME',
      collapsible: true,
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'about-me' }],
    },

    // FEATURED
    {
      type: 'html',
      value: '<div class="sidebar__section">FEATURED</div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'GitHub API Docs',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Guides & Fundamentals',
          collapsible: true,
          collapsed: false,
          items: [
            'github-api-doc/guides/overview',
            'github-api-doc/guides/quick-start',
            'github-api-doc/guides/authentication',
            'github-api-doc/guides/pagination',
            'github-api-doc/guides/errors-and-status-codes',
            'github-api-doc/guides/validation-and-sources',
          ],
        },
        {
          type: 'category',
          label: 'API Reference',
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'Endpoints',
              collapsible: true,
              collapsed: false,
              items: ['github-api-doc/reference/endpoints/list-issues'],
            },
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Case Studies',
      collapsible: true,
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'case-studies' }],
    },

    // TECHNICAL DOCUMENTATION (Samples)
    {
      type: 'html',
      value: '<div class="sidebar__section">TECHNICAL DOCUMENTATION</div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Technical Documentation',
      collapsible: true,
      collapsed: false, // abre automaticamente
      items: [{ type: 'autogenerated', dirName: 'documentation-samples' }],
    },
  ],
};

module.exports = sidebars;
