/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // =====================
    // HOME
    // =====================
    {
      type: 'category',
      label: 'HOME',
      collapsible: false,
      items: [
        'intro',
        'about-me/about-me',
        'about-me/documentation-approach',
      ],
    },

    // =====================
    // FEATURED
    // =====================
    {
      type: 'category',
      label: 'FEATURED',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'GitHub API Docs',
          collapsible: true,
          collapsed: false, // abre tudo
          items: [
            {
              type: 'category',
              label: 'Guides & Fundamentals',
              collapsible: true,
              collapsed: false, // abre tudo
              items: [
                'github-api-doc/guides/overview',
                'github-api-doc/guides/quick-start',
                'github-api-doc/guides/authentication',
                'github-api-doc/guides/pagination',
                'github-api-doc/guides/errors-and-status-codes',
                'github-api-doc/guides/validation-and-sources',
              ],
            },
            {
              type: 'category',
              label: 'API Reference',
              collapsible: true,
              collapsed: false, // abre tudo
              items: [
                {
                  type: 'category',
                  label: 'Endpoints',
                  collapsible: true,
                  collapsed: false, // abre tudo
                  items: [
                    'github-api-doc/reference/endpoints/list-issues',
                  ],
                },
              ],
            },
          ],
        },
      ],
    },

    // =====================
    // CASE STUDIES
    // =====================
    {
      type: 'category',
      label: 'CASE STUDIES',
      collapsible: true,
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'case-studies' }],
    },

    // =====================
    // TECHNICAL DOCUMENTATION
    // =====================
    {
      type: 'category',
      label: 'TECHNICAL DOCUMENTATION',
      collapsible: true,
      collapsed: false, // você pediu pra abrir automaticamente
      items: [{ type: 'autogenerated', dirName: 'documentation-samples' }],
    },
  ],
};

module.exports = sidebars;
